[project]
name = "zerotohero"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "notebook>=7.4.3",
    "torch>=2.7.0",
]
